{{- if .Values.messageRouter.enabled -}}
{{- $serviceName := "message-router" -}}
{{- $replica := .Values.messageRouter.replica | default 1 -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $serviceName }}
  labels:
    - service: {{ $serviceName }}
    {{- include "chatserver.labels" . | nindent 4 -}}
spec:
  replicas: {{ $replica }}
  selector:
    matchLabels:
      - service: {{ $serviceName }}
      {{- include "chatserver.selectorLabels" . | nindent 6 -}}
  template:
    metadata:
      {{- with .Values.podAnnotations -}}
      annotations:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
      labels:
        - service: {{ $serviceName }}
        {{- include "chatserver.selectorLabels" . | nindent 8 -}}
    spec:
      {{- with .Values.imagePullSecrets -}}
      imagePullSecrets:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
      serviceName: {{ $serviceName }}
      serviceAccountName: {{ include "chatserver.serviceAccountName" . }}
      containers:
        - name: {{ $serviceName }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 -}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
          args:
            - /app/services/message-router-ms/message-router-ms.js
            - --app-name="${hostname}"
            - --send-message-topic={{ .Values.topic.sendMessage }}
            - --new-message-topic={{ .Values.topic.message }}
            - --system-message-topic={{ .Values.topic.systemMessage }}
            - --group-message-topic={{ .Values.topic.groupMessage }}
            {{ include "eventStore.option" (dict "consumerGroup" "message-router") | nindent 12 }}
{{- end -}}          
