{{- if .Values.profileMs.enabled -}}
{{ $serviceName := "profile" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
spec:
  selector:
    - service: {{ $serviceName }}
    {{- include "chatserver.labels" . | nindent 4 -}}
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end -}}
