
image:
  file: .gitpod/Dockerfile

ports:
  - port: 8080
    onOpen: open-browser

tasks:
  - init: yarn install
  - name: Kafka 
    command: > 
      chmod +x deployment/scripts/init-kafka.bash &&
      cp .env.tmpl .env &&
      KAFKA_HOME=/kafka &&
      ./deployment/scripts/init-kafka.bash $KAFKA_HOME .env
  - name: Nginx
    command: nginx
  - name: mongodb
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: redis
    command:  redis-server 
  - name: firebase
    command: cd ./deployment/config/firebase && cp service.json.example service.json

vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
