image:
  file: .gitpod/Dockerfile

ports:
  - port: 8080
    onOpen: open-browser

tasks:
  - init: yarn install
  - name: Kafka
    init: chmod +x deployment/scripts/*.bash && ./deployment/scripts/setup.bash
    command: >
      KAFKA_HOME=/kafka &&
      ./deployment/scripts/init-kafka.bash $KAFKA_HOME .env
  - name: Nats
    command: nats -js
  - name: Nginx
    command: export NGINX_DOCROOT="${GITPOD_REPO_ROOT}/www" && nginx
  - name: mongodb
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
  - name: redis
    command: redis-server

vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
