
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-browser

tasks:
  - init: yarn install
  - name: Kafka 
    command: > 
      chmod +x deployment/dev/scripts/init-kafka.bash &&
      cp .env.tmpl .env &&
      KAFKA_HOME=/kafka &&
      ./deployment/dev/scripts/init-kafka.bash $KAFKA_HOME .env
  - name: Nginx
    command: nginx
  - name: mongodb
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data

vscode:
  extensions:
    - editorconfig.editorconfig