{{- if .Values.notificationMs.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "firebase-admin-cred"
data:
  service.json: |
  {{ .Files.Get .Values.firebase.adminCredentialPath }}
{{- end -}}
