{{- if .Values.notificationMs.enabled -}}
{{- $serviceName := "notification" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    - service: {{ $serviceName }}
    {{- include "chatserver.labels" . | nindent 4 -}}
{{- end -}}
