version: "3.9"

services:
  nginx:
    image: nginx:stable
    volumes:
      - ${CONFIG_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  gateway:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    entrypoint: node
    command: /app/services/connection-gateway/gateway.js --host=0.0.0.0 --app-name=ws-gateway --gateway-name=gateway-1 --kafka-client-id=gateway-1 --kafka-consumer-group=${CONSUMER_GROUP_GATEWAY} --kafka-user-connection-state-topic=${TOPIC_USER_CONNECTION_STATE} --kafka-new-message-topic=${TOPIC_NEW_MESSAGE} --kafka-broker-list='${BROKER_LIST}' --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD}

  message-delivery:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    volumes:
      - '${CONFIG_DIR}/discovery_service/services.json:/app/discovery_service.json'
    entrypoint: node
    command: /app/services/message-delivery/message-delivery-ms.js --app-name=message-delivery --kafka-client-id=message-delivery-1 --kafka-consumer-group=${TOPIC_USER_CONNECTION_STATE} --kafka-user-connection-state-topic=${TOPIC_USER_CONNECTION_STATE} --kafka-send-message-topic=${TOPIC_SEND_MESSAGE} --kafka-ack-topic=${TOPIC_ACK_MESSAGE} --kafka-offline-message-topic=${TOPIC_OFFLINE_MESSAGE} --service-discovery-path=/app/discovery_service.json --kafka-broker-list=${BROKER_LIST} --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD} --cache-type=redis --redis-endpoint=${REDIS_ENDPOINT} --mongo-url=${MONGO_URL} --mongo-user=${MONGO_USER} --mongo-password=${MONGO_PASSWORD} --mongo-auth

  message_router:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    entrypoint: node
    command: /app/services/message-router-ms/message-router-ms.js --app-name=message-router-1 --kafka-client-id=message-router-1 --kafka-consumer-group=${CONSUMER_GROUP_MESSAGE_ROUTER} --kafka-send-message-topic=${TOPIC_SEND_MESSAGE} --kafka-new-message-topic=${TOPIC_NEW_MESSAGE} --kafka-ack-topic=${TOPIC_ACK_MESSAGE} --kafka-group-message-topic=${TOPIC_NEW_GROUP_MS} --kafka-broker-list=${BROKER_LIST} --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD}

  profile:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    entrypoint: node
    command: /app/services/profile-ms/profile-ms.js --app-name=profile-ms-1 --host=0.0.0.0 --port=4000 --mongo-url=${MONGO_URL} --mongo-user=${MONGO_USER} --mongo-password=${MONGO_PASSWORD} --mongo-auth --firebase-project-id=${FIREBASE_PROJECT_ID} --kafka-broker-list=${BROKER_LIST} --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD} --kafka-new-login-topic=${TOPIC_NEW_LOGIN}

  group:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    entrypoint: node
    command: >
      /app/services/group-ms/group-ms.js --app-name=group-ms-1 --host=0.0.0.0 --port=4002 --mongo-url=${MONGO_URL} --mongo-user=${MONGO_USER} --mongo-password=${MONGO_PASSWORD} --mongo-auth --kafka-broker-list=${BROKER_LIST} --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD} --kafka-client-id=group-1 --kafka-new-group-message-topic=${TOPIC_NEW_GROUP_MS} --json-server-port=${GROUP_MS_JSON_PORT}

  group_message_router:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    entrypoint: node
    command: /app/services/message-router-ms/group-message-router-ms.js --app-name=group-message-router-1 --kafka-broker-list=${BROKER_LIST} --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD} --kafka-client-id=group-message-router-1 --kafka-consumer-group=${CONSUMER_GROUP_GROUP_MESSAGE_ROUTER} --kafka-new-group-message-topic=${TOPIC_NEW_GROUP_MS} --kafka-send-message-topic=${TOPIC_SEND_MESSAGE} --kafka-ack-topic=${TOPIC_ACK_MESSAGE} --mongo-url=${MONGO_URL} --mongo-user=${MONGO_USER} --mongo-password=${MONGO_PASSWORD} --mongo-auth --kafka-persistence-message-topic=${TOPIC_OFFLINE_MESSAGE}

  notification:
    image: ramank775/chatserver:${CHAT_SERVER_TAG}
    volumes:
      - ${CONFIG_DIR}/firebase/service.json:/app/.service.json:ro
    entrypoint: node
    command: /app/services/notification-ms/notification-ms.js --app-name=notification-ms-1 --mongo-url=${MONGO_URL} --mongo-user=${MONGO_USER} --mongo-password=${MONGO_PASSWORD} --mongo-auth --firebase-admin-credential-json-path=/app/.service.json --kafka-broker-list=${BROKER_LIST} --kafka-security-protocol=${KAFKA_SECURITY_PROTOCOL} --kafka-sasl-username=${KAFKA_SASL_USERNAME} --kafka-sasl-password=${KAFKA_SASL_PASSWORD} --kafka-consumer-group=notification-ms --kafka-new-login-topic=${TOPIC_NEW_LOGIN} --kafka-offline-message-topic=${TOPIC_OFFLINE_MESSAGE} --db-app-initial=${PERSISTENCE_MESSAGE_MS_INITIAL}
